version: '3.8'

services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=leave-management-system
      - MYSQL_ROOT_PASSWORD=cnpmnc@241
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/leave-management-system?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=cnpmnc@241
    depends_on:
      - db
    networks:
      - app-network


volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge